### PR TITLE
Update rpb-spatial from CSV/XLS file in RPB-173

### PR DESCRIPTION
**Pull request by fsteeg**
Created via https://github.com/hbz/rpb/pull/86

See https://jira.hbz-nrw.de/browse/RPB-173

### CODE REVIEW

**Comment by fsteeg** [comment]
Hm, build fails when including entries not used in RPB due to missing broader concepts, e.g. `n140060680102` has broader `n14006068`, which is not in the SKOS. I think this is caused by errors in the original CSV/XLS, will investigate.

**Comment by fsteeg** [comment]
With fixed IDs the build now works, but the page doesn't look right:

https://skohub.io/hbz/lobid-vocabs/heads/rpb-173-updateRpbSpatial/rpb.lobid.org/spatial.html

"No label for language "" provided", and can't expand the items.

**Comment by acka47** [comment]
This is a problem with SkoHub Vocabs, I assume in combination with vocabularies that use hash URIs. it works for me when:

- going to the overview page: https://skohub.io/hbz/lobid-vocabs/heads/rpb-173-updateRpbSpatial/
- clicking on the RPB Raumsystematik (sometimes I have to click several times resp. wait a while until the page is served).
- Voilà it looks good:
image

**Comment by fsteeg** [comment]
> sometimes I have to click several times resp. wait a while until the page is served

Hm, for me, it only comes up when I open in a new tab, but then again ""No label for language "" provided"". Could this be related to my system locale being set to `en`? I tried adding `de` to my browser languages, I see that I'm sending `Accept-Language: de,en...`, but still the same, and the overview page remains English.

**Comment by fsteeg** [comment]
Oh, now I go it it working (clicked in overview, then Reload/F5 did the trick for me).

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
