### PR TITLE
Update LBZ notations.

### PR DESCRIPTION
**Pull request by blackwinter**
We're considering switching our [LBZ notation mapping](https://github.com/hbz/limetrans/blob/aad413e8c583e3a64340d52ea725472391a32e08/src/main/resources/transformation/maps/alma-taxonomy.fix#L14854) in Limetrans to the SKOS one maintained here. But there were some differences, mainly in the labels. These should probably be clarified.

Diffed against mapping reported to DigiBib (2020-12-28, DOX-917).
    
Additional notations not removed:
    
- 136 Landeskunde Region Trier (6a2c4c4)
- 137 Landeskunde Rheinhessen (6a2c4c4)
- 139 Belegexemplare Rheinland-Pfalz (6a2c4c4)
- 146 Pflichtexemplar Region Trier (6a2c4c4)
- 147 Pflichtexemplar Rheinhessen (6a2c4c4)
- 160 Kinder-/Jugendliteratur (e3ec4fc)
- 161 Kinder-/Jugendsachbuch (e3ec4fc)

----

The first commit is unrelated, but came up during editing the file. May be fixed separately.

### CODE REVIEW

**Comment by acka47** [comment]
@blackwinter , it definitely makes sense to move to the SKOS file(s). I think we discussed with LBZ that they would be using these as single source of truth. However, they are not (yet) perfect, see e.g. https://github.com/hbz/lobid-resources/issues/2057 which will probably result in some missing notations being added.

With regard to the review of this PR, the final say should have LBZ people who already have been working in this repo.

**Comment by acka47** [comment]
The changes this PR ewould bring to the vocab can also be viewed with SkoHub Vocabs at https://skohub.io/hbz/lobid-vocabs/heads/wip-updateLBZNotations/w3id.org/lobid/rpb2.html

**Comment by blackwinter** [comment]
> With regard to the review of this PR, the final say should have LBZ people who already have been working in this repo.

Sure, just let me know how you want to proceed. Should I split this pull request or continue as it is? Who would be the reviewers to be assigned?

**Comment by blackwinter** [comment]
Moved to hbz/lbz-vocabs#3.

**Pull request closed without merging**
