### PR TITLE
Adjust namespace for NWBib Sachsystematik

### PR DESCRIPTION
**Pull request by acka47**
For sake of consistency, analogous to the already changed NWBib spatial namespace.

### CODE REVIEW

**Comment by fsteeg** [comment]
Two things that I noticed:

- The `skos:inScheme <http://purl.org/lobid/nwbib> ;` statements need to be updated
- We still have the discrepancy of e.g. `https://nwbib.de/subjects#N101000` [in the data](http://lobid.org/resources/HT021193047.json) vs. `https://nwbib.de/subjects#s101000` in the TTL file (`N` vs. `s`)

**Comment by acka47** [comment]
Very good that you are paying more attention than me. I addressed your feedback in 940d85c .

**Comment by fsteeg** [comment]
> Very good that you are paying more attention than me.

I've had some computational help (was getting no hits in the UI, looks good now).

Will merge and deploy to test and production.

**Comment by fsteeg** [comment]
Deployed to https://test.nwbib.de/subjects ([ttl](https://test.nwbib.de/subjects.ttl)) & https://nwbib.de/subjects ([ttl](https://nwbib.de/subjects.ttl)).

**Comment by acka47** [comment]
Looks very good.

**Pull request merged**
