### PR TITLE
Link SkoHub Vocabs instead of NWBib (#196)

### PR DESCRIPTION
**Pull request by HMetzner**

### CODE REVIEW

**Comment by acka47** [comment]
Hm, this does not seem to work as intended, see e.g. https://test.skohub.io/hbz/lobid-vocabs/heads/196-linkSkoHubVocabsInsteadOfNWBib/nwbib.de/subjects.de.html#N706040

In the branch, relative IDs are used:

https://github.com/hbz/lobid-vocabs/blob/9815c69bcadc0d44a40efdd4811aaa741ef2b63b/nwbib/nwbib.ttl#L5493-L5500

but the actual links in the browser point to nwbib.de/subjects.

@sroertgen do you know why it behaves like this?

**Comment by HMetzner** [comment]
Maybe it happened because I just deleted "https://nwbib.de/subjects" in front of #N706041 instead of typing #N706041 at once?

**Comment by sroertgen** [comment]
I forked this branch and had the same issue you had. After I merged the file to master, the issue disappeared and the links are working like expected, see: https://test.skohub.io/sroertgen/lobid-vocabs/heads/master/nwbib.de/subjects.de.html#N706040

I suspect some weird caching somewhere and will have to investigate that.

**Comment by sroertgen** [comment]
I suspect that the branch info is not correctly used by SkoHub Webhook. It seems to fetch data from the master even if commit comes from a branch. Will open an issue for that.

**Comment by acka47** [comment]
Ok, so we can (and should) merge this PR, I guess?

**Comment by sroertgen** [comment]
Yes. And I'm fixing SkoHub Webhook

**Comment by sroertgen** [comment]
Seems to work though 

- The link to "Sagen" is missing a "N" after the hash

still is there. Will you take care of that @HMetzner @acka47  ?

I fixed the issue as well. Needs to be though. Good you found out!

**Pull request merged**
